### ISSUE TITLE
make file Raspbian error 

### ISSUE THREAD

**Issue by qureshiowais91** [muratdemirtas/MT7601u#12]
sudo make clean && make all && make install 
make -C src/ clean
make[1]: Entering directory '/home/pi/MT7601u/src'
cp -f os/linux/Makefile.clean os/linux/Makefile
make -C os/linux clean
make[2]: Entering directory '/home/pi/MT7601u/src/os/linux'
rm -f ../../common/*.o
rm -f ../../common/.*.cmd .*.flags .*.d
rm -f ../../os/linux/*.o *.ko *.mod.o *.mod.c
rm -f ../../os/linux/.*.cmd .*.flags .*.d
rm -fr ../../os/linux/.tmp_versions
rm -f ../../os/linux/Module.symvers
rm -f ../../os/linux/Modules.symvers
rm -f ../../os/linux/Module.markers
rm -f ../../os/linux/modules.order
rm -f ../../chips/*.o
rm -f ../../chips/.*.cmd .*.flags .*.d
rm -f ../../rate_ctrl/*.o
rm -f ../../rate_ctrl/.*.cmd .*.flags .*.d
rm -f ../../ate/common/*.o
rm -f ../../ate/common/.*.cmd .*.flags .*.d
rm -f ../../ate/chips/*.o
rm -f ../../ate/chips/.*.cmd .*.flags .*.d
rm -f ../../phy/*.o
rm -f ../../phy/.*.cmd .*.flags .*.d
rm -f ../../mac/*.o
rm -f ../../mac/.*.cmd .*.flags .*.d
rm -f ../../mcu/*.o
rm -f ../../mcu/.*.cmd .*.flags .*.d
rm -f ../../mgmt/*.o
rm -f ../../mgmt/.*.cmd .*.flags .*.d
rm -f ../../naf/*.o
rm -f ../../naf/.*.cmd .*.flags .*.d
rm -f ../../ap/*.o
rm -f ../../ap/.*.cmd .*.flags .*.d
make[2]: Leaving directory '/home/pi/MT7601u/src/os/linux'
rm -rf os/linux/Makefile
make[1]: Leaving directory '/home/pi/MT7601u/src'
make -C src/ osutil
make[1]: Entering directory '/home/pi/MT7601u/src'
cp -f os/linux/Makefile.6.util /home/pi/MT7601u/src/os/linux/Makefile
cp: cannot create regular file '/home/pi/MT7601u/src/os/linux/Makefile': Permission denied
Makefile:510: recipe for target 'osutil' failed
make[1]: *** [osutil] Error 1
make[1]: Leaving directory '/home/pi/MT7601u/src'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by darkfriday** [comment]
~~sudo make clean && make all && make install~~ :x:
sudo make clean && __sudo__ make all &&  __sudo__ make install :white_check_mark:

**Comment by truckflipper** [comment]
> ~sudo make clean && make all && make install~ x
> sudo make clean && **sudo** make all && **sudo** make install white_check_mark
