### ISSUE TITLE
Compilation errors.

### ISSUE THREAD

**Issue by Jimmy01240397** [muratdemirtas/MT7601u#16]
How should I did when I get 
No rule to make target '/root/MT7601u/src/os/linux/../../common/rt_os_util.o', needed by '/root/MT7601u/src/os/linux/rtutil7601Uap.o'.  Stop.

root@debian:~/MT7601u# make all
make -C src/ osutil
make[1]: Entering directory '/root/MT7601u/src'
cp -f os/linux/Makefile.6.util /root/MT7601u/src/os/linux/Makefile
make -C /lib/modules/4.19.0-10-amd64/build SUBDIRS=/root/MT7601u/src/os/linux modules
make[2]: Entering directory '/usr/lib/modules/4.19.0-10-amd64/build'
make[3]: *** No rule to make target '/root/MT7601u/src/os/linux/../../common/rt_os_util.o', needed by '/root/MT7601u/src/os/linux/rtutil7601Uap.o'.  Stop.
make[2]: *** [Makefile:1545: _module_/root/MT7601u/src/os/linux] Error 2
make[2]: Leaving directory '/usr/lib/modules/4.19.0-10-amd64/build'
make[1]: *** [Makefile:512: osutil] Error 2
make[1]: Leaving directory '/root/MT7601u/src'
make: *** [Makefile:2: all] Error 2

**Comment by cheloveg** [comment]
Get same error, how did you fixed this?
